spring:
  application:
    name: Spring-boot-api
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_boot_api?useTimezone=true&serverTimezone=UTC
      username: root
      password:
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
      show-sql: false
      open-in-view: false
